In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Current folder:", os.getcwd())
print("Libraries imported successfully")

Current folder: /Users/vanearellano/Documents/GitHub/education-income-canada-analysis/notebooks
Libraries imported successfully

In [2]:
import pandas as pd

df = pd.read_csv("../data/98100411.csv")

df.head()

,REF_DATE,GEO,DGUID,Statistics (3),Gender (3),Age (15A),Income year (2),"Highest certificate, diploma or degree (16)",Coordinate,Employment income statistics (7):Total - Employment income statistics[1],...,Employment income statistics (7):Median employment income ($)[3],Symbol.2,Employment income statistics (7):Average employment income ($)[4],Symbol.3,"Employment income statistics (7):With wages, salaries and commissions[5]",Symbol.4,"Employment income statistics (7):Median wages, salaries and commissions ($)[6]",Symbol.5,"Employment income statistics (7):Average wages, salaries and commissions ($)[7]",Symbol.6
0,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,"Total - Highest certificate, diploma or degree",1.1.1.1.1.1,30335920.0,...,37200.0,NaN,50280.0,NaN,19392225.0,NaN,40000.0,NaN,51950.0,NaN
1,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,"No certificate, diploma or degree",1.1.1.1.1.2,4899580.0,...,15600.0,NaN,26880.0,NaN,1931005.0,NaN,17200.0,NaN,28080.0,NaN
2,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,High (secondary) school diploma or equivalency...,1.1.1.1.1.3,8097295.0,...,25000.0,NaN,35520.0,NaN,5019180.0,NaN,27000.0,NaN,36720.0,NaN
3,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,"Postsecondary certificate, diploma or degree",1.1.1.1.1.4,17339045.0,...,47200.0,NaN,60000.0,NaN,12442045.0,NaN,50000.0,NaN,61750.0,NaN
4,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,Postsecondary certificate or diploma below bac...,1.1.1.1.1.5,9252800.0,...,41200.0,NaN,48600.0,NaN,6448935.0,NaN,43600.0,NaN,50680.0,NaN

In [3]:
df.shape

(23621760, 23)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23621760 entries, 0 to 23621759
Data columns (total 23 columns):
 #   Column                                                                           Dtype
---  ------                                                                           -----
 0   REF_DATE                                                                         int64
 1   GEO                                                                              object
 2   DGUID                                                                            object
 3   Statistics (3)                                                                   object
 4   Gender (3)                                                                       object
 5   Age (15A)                                                                        object
 6   Income year (2)                                                                  int64
 7   Highest certificate, diploma or degree (16)                                      object
 8   Coordinate                                                                       object
 9   Employment income statistics (7):Total - Employment income statistics[1]         float64
 10  Symbol                                                                           object
 11  Employment income statistics (7):With employment income[2]                       float64
 12  Symbol.1                                                                         object
 13  Employment income statistics (7):Median employment income ($)[3]                 float64
 14  Symbol.2                                                                         object
 15  Employment income statistics (7):Average employment income ($)[4]                float64
 16  Symbol.3                                                                         object
 17  Employment income statistics (7):With wages, salaries and commissions[5]         float64
 18  Symbol.4                                                                         object
 19  Employment income statistics (7):Median wages, salaries and commissions ($)[6]   float64
 20  Symbol.5                                                                         object
 21  Employment income statistics (7):Average wages, salaries and commissions ($)[7]  float64
 22  Symbol.6                                                                         object
dtypes: float64(7), int64(2), object(14)
memory usage: 4.0+ GB

In [5]:
df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Statistics (3)', 'Gender (3)', 'Age (15A)',
       'Income year (2)', 'Highest certificate, diploma or degree (16)',
       'Coordinate',
       'Employment income statistics (7):Total - Employment income statistics[1]',
       'Symbol', 'Employment income statistics (7):With employment income[2]',
       'Symbol.1',
       'Employment income statistics (7):Median employment income ($)[3]',
       'Symbol.2',
       'Employment income statistics (7):Average employment income ($)[4]',
       'Symbol.3',
       'Employment income statistics (7):With wages, salaries and commissions[5]',
       'Symbol.4',
       'Employment income statistics (7):Median wages, salaries and commissions ($)[6]',
       'Symbol.5',
       'Employment income statistics (7):Average wages, salaries and commissions ($)[7]',
       'Symbol.6'],
      dtype='object')

In [6]:
df.isnull().sum()

REF_DATE                                                                                  0
GEO                                                                                       0
DGUID                                                                                     0
Statistics (3)                                                                            0
Gender (3)                                                                                0
Age (15A)                                                                                 0
Income year (2)                                                                           0
Highest certificate, diploma or degree (16)                                               0
Coordinate                                                                                0
Employment income statistics (7):Total - Employment income statistics[1]            6700320
Symbol                                                                             10762612
Employment income statistics (7):With employment income[2]                          6700320
Symbol.1                                                                           10170934
Employment income statistics (7):Median employment income ($)[3]                    6700320
Symbol.2                                                                            8938700
Employment income statistics (7):Average employment income ($)[4]                   6700320
Symbol.3                                                                           10161082
Employment income statistics (7):With wages, salaries and commissions[5]            6700320
Symbol.4                                                                            9996554
Employment income statistics (7):Median wages, salaries and commissions ($)[6]      6700320
Symbol.5                                                                            8794458
Employment income statistics (7):Average wages, salaries and commissions ($)[7]     6700320
Symbol.6                                                                            9983972
dtype: int64

In [7]:
pd.set_option("display.max_columns", None)
df.head()

,REF_DATE,GEO,DGUID,Statistics (3),Gender (3),Age (15A),Income year (2),"Highest certificate, diploma or degree (16)",Coordinate,Employment income statistics (7):Total - Employment income statistics[1],Symbol,Employment income statistics (7):With employment income[2],Symbol.1,Employment income statistics (7):Median employment income ($)[3],Symbol.2,Employment income statistics (7):Average employment income ($)[4],Symbol.3,"Employment income statistics (7):With wages, salaries and commissions[5]",Symbol.4,"Employment income statistics (7):Median wages, salaries and commissions ($)[6]",Symbol.5,"Employment income statistics (7):Average wages, salaries and commissions ($)[7]",Symbol.6
0,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,"Total - Highest certificate, diploma or degree",1.1.1.1.1.1,30335920.0,NaN,21127690.0,NaN,37200.0,NaN,50280.0,NaN,19392225.0,NaN,40000.0,NaN,51950.0,NaN
1,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,"No certificate, diploma or degree",1.1.1.1.1.2,4899580.0,NaN,2170740.0,NaN,15600.0,NaN,26880.0,NaN,1931005.0,NaN,17200.0,NaN,28080.0,NaN
2,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,High (secondary) school diploma or equivalency...,1.1.1.1.1.3,8097295.0,NaN,5450335.0,NaN,25000.0,NaN,35520.0,NaN,5019180.0,NaN,27000.0,NaN,36720.0,NaN
3,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,"Postsecondary certificate, diploma or degree",1.1.1.1.1.4,17339045.0,NaN,13506615.0,NaN,47200.0,NaN,60000.0,NaN,12442045.0,NaN,50000.0,NaN,61750.0,NaN
4,2021,Canada,2021A000011124,Count,Total - Gender,Total - Age,2020,Postsecondary certificate or diploma below bac...,1.1.1.1.1.5,9252800.0,NaN,7002780.0,NaN,41200.0,NaN,48600.0,NaN,6448935.0,NaN,43600.0,NaN,50680.0,NaN

In [8]:
df.describe()

,REF_DATE,Income year (2),Employment income statistics (7):Total - Employment income statistics[1],Employment income statistics (7):With employment income[2],Employment income statistics (7):Median employment income ($)[3],Employment income statistics (7):Average employment income ($)[4],"Employment income statistics (7):With wages, salaries and commissions[5]","Employment income statistics (7):Median wages, salaries and commissions ($)[6]","Employment income statistics (7):Average wages, salaries and commissions ($)[7]"
count,23621760.0,23621760.0,1.692144e+07,1.692144e+07,1.692144e+07,1.692144e+07,1.692144e+07,1.692144e+07,1.692144e+07
mean,2021.0,2019.5,1.025235e+03,7.777683e+02,1.157228e+04,1.789338e+04,7.212171e+02,1.162255e+04,1.780744e+04
std,0.0,0.5,4.520808e+04,3.523641e+04,2.408332e+04,3.082862e+04,3.269729e+04,2.423740e+04,3.084459e+04
min,2021.0,2019.0,0.000000e+00,0.000000e+00,-6.655910e+05,-1.244208e+06,0.000000e+00,-3.981250e+05,-1.429435e+06
25%,2021.0,2019.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2021.0,2019.5,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2021.0,2020.0,7.000000e+01,5.300000e+01,9.400000e+03,3.255600e+04,4.800000e+01,7.400000e+03,3.276000e+04
max,2021.0,2020.0,3.033661e+07,2.124712e+07,8.335910e+05,8.044208e+06,1.969359e+07,7.065740e+05,8.521992e+06

In [9]:
df_selected = df_selected.rename(columns={
    "GEO": "geo",
    "Gender (3)": "gender",
    "Age (15A)": "age_group",
    "Income year (2)": "income_year",
    "Highest certificate, diploma or degree (16)": "education_level",
    "Employment income statistics (7):Median employment income ($)[3]": "median_employment_income",
    "Employment income statistics (7):Average employment income ($)[4]": "average_employment_income"
})

df_selected.head()

NameError: name 'df_selected' is not defined

In [ ]:
df.head()

In [ ]:
df_selected = df[
    [
        "GEO",
        "Gender (3)",
        "Age (15A)",
        "Income year (2)",
        "Highest certificate, diploma or degree (16)",
        "Employment income statistics (7):Median employment income ($)[3]",
        "Employment income statistics (7):Average employment income ($)[4]"
    ]
]

df_selected.head()

In [ ]:
df_selected.head()

In [ ]:
df_selected.columns

In [ ]:
df_selected = df_selected.rename(columns={
    "GEO": "geo",
    "Gender (3)": "gender",
    "Age (15A)": "age_group",
    "Income year (2)": "income_year",
    "Highest certificate, diploma or degree (16)": "education_level",
    "Employment income statistics (7):Median employment income ($)[3]": "median_employment_income",
    "Employment income statistics (7):Average employment income ($)[4]": "average_employment_income"
})

df_selected.columns

In [ ]:
df_selected["geo"].value_counts().head(20)

In [ ]:
df_selected["gender"].value_counts()

In [ ]:
df_selected["age_group"].value_counts()

In [ ]:
df_selected["income_year"].value_counts()

In [ ]:
df_selected["education_level"].value_counts()

In [ ]:
df_selected["age_group"].value_counts()

In [ ]:
df_selected["income_year"].value_counts()

In [ ]:
df_analysis = df_selected[
    (df_selected["geo"] == "Canada") &
    (df_selected["gender"] == "Total - Gender")
]

In [ ]:
df_selected["income_year"].value_counts()

In [ ]:
df_analysis = df_selected[
    (df_selected["geo"] == "Canada") &
    (df_selected["gender"] == "Total - Gender") &
    (df_selected["age_group"] == "25 to 64 years")
]

df_analysis.head()

In [ ]:
df_analysis = df_selected[
    (df_selected["geo"] == "Canada") &
    (df_selected["gender"] == "Total - Gender") &
    (df_selected["age_group"] == "25 to 64 years") &
    (df_selected["income_year"] == 2020)
]

df_analysis.head()

In [ ]:
df_analysis.shape

In [ ]:
df_analysis["education_level"].value_counts()

In [ ]:
df_analysis.head(20)

In [ ]:
df_analysis.duplicated().sum()

In [ ]:
df_selected["statistics"].value_counts()

In [ ]:
df_selected.columns

In [ ]:
df_selected = df[
    [
        "GEO",
        "Statistics (3)",
        "Gender (3)",
        "Age (15A)",
        "Income year (2)",
        "Highest certificate, diploma or degree (16)",
        "Employment income statistics (7):Median employment income ($)[3]",
        "Employment income statistics (7):Average employment income ($)[4]"
    ]
]

df_selected = df_selected.rename(columns={
    "GEO": "geo",
    "Statistics (3)": "statistics",
    "Gender (3)": "gender",
    "Age (15A)": "age_group",
    "Income year (2)": "income_year",
    "Highest certificate, diploma or degree (16)": "education_level",
    "Employment income statistics (7):Median employment income ($)[3]": "median_employment_income",
    "Employment income statistics (7):Average employment income ($)[4]": "average_employment_income"
})

df_selected.head()

In [ ]:
df_selected.columns

In [ ]:
df_selected["statistics"].value_counts()

In [ ]:
df_analysis = df_selected[
    (df_selected["geo"] == "Canada") &
    (df_selected["statistics"] == "Count") &
    (df_selected["gender"] == "Total - Gender") &
    (df_selected["age_group"] == "25 to 64 years") &
    (df_selected["income_year"] == 2020)
]

df_analysis.head()

In [ ]:
df_analysis.shape

In [ ]:
df_analysis["education_level"].value_counts()

In [ ]:
df_analysis[
    [
        "education_level",
        "median_employment_income",
        "average_employment_income"
    ]
]

In [ ]:
income_by_education = df_analysis_clean[
    [
        "education_level",
        "median_employment_income",
        "average_employment_income"
    ]
].sort_values(by="median_employment_income", ascending=False)

income_by_education

In [ ]:
df_analysis_clean = df_analysis[
    df_analysis["education_level"] != "Total - Highest certificate, diploma or degree"
]

df_analysis_clean.shape

In [ ]:
income_by_education = df_analysis_clean[
    [
        "education_level",
        "median_employment_income",
        "average_employment_income"
    ]
].sort_values(by="median_employment_income", ascending=False)

income_by_education

In [ ]:
plt.figure(figsize=(12, 7))

plt.barh(
    income_by_education["education_level"],
    income_by_education["median_employment_income"]
)

plt.xlabel("Median Employment Income ($)")
plt.ylabel("Educational Attainment")
plt.title("Median Employment Income by Educational Attainment in Canada, 2020")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(12, 7))

plt.barh(
    income_by_education["education_level"],
    income_by_education["median_employment_income"]
)

plt.xlabel("Median Employment Income ($)")
plt.ylabel("Educational Attainment")
plt.title("Median Employment Income by Educational Attainment in Canada, 2020")
plt.gca().invert_yaxis()
plt.tight_layout()

plt.savefig("../images/median_income_by_education_canada_2020.png", bbox_inches="tight")
plt.show()

The graph shows the median employment income by educational attainment level in Canada in 2020.

Overall, the results suggest that employment income varies across education levels. Individuals with an earned doctorate and those with professional degrees, such as medicine, dentistry, veterinary medicine, or optometry, show some of the highest median employment income levels. In contrast, individuals with no certificate, diploma, or degree have the lowest median employment income.

In 2020, the highest median employment income was approximately $80,000 CAD per year, while individuals with no certificate, diploma, or degree had a median employment income close to $20,000 CAD per year.

Education levels such as college, apprenticeship, trades certificates, and postsecondary certificates below the bachelor level show a similar income pattern, with median employment income around $40,000 CAD per year. Finally, individuals with a bachelor's degree, university certificates, or higher education levels tend to show higher median employment income, generally around $60,000 CAD or more per year.

These results suggest that educational attainment is associated with differences in employment income in Canada. However, this relationship should not be interpreted as direct causation, since other factors such as work experience, occupation, province, industry, and immigration status may also influence income.

In [ ]:
import os
os.listdir("../images")

In [ ]:
income_by_education_avg = df_analysis_clean[
    [
        "education_level",
        "median_employment_income",
        "average_employment_income"
    ]
].sort_values(by="average_employment_income", ascending=False)

income_by_education_avg

In [ ]:
plt.figure(figsize=(12, 7), facecolor="white")

plt.barh(
    income_by_education_avg["education_level"],
    income_by_education_avg["average_employment_income"]
)

plt.xlabel("Average Employment Income ($)", color="black")
plt.ylabel("Educational Attainment", color="black")
plt.title("Average Employment Income by Educational Attainment in Canada, 2020", color="black")

plt.xticks(color="black")
plt.yticks(color="black")

plt.gca().set_facecolor("white")
plt.gca().invert_yaxis()
plt.tight_layout()

plt.savefig(
    "../images/average_income_by_education_canada_2020.png",
    bbox_inches="tight",
    facecolor="white"
)

plt.show()

The graph shows the average employment income by educational attainment level in Canada in 2020.

Overall, the results suggest that average employment income varies across education levels. In 2020, individuals with a degree in medicine, dentistry, veterinary medicine, or optometry had the highest average employment income, at approximately $109,900 CAD per year. Individuals with an earned doctorate also showed a high average employment income, at around $103,700 CAD per year.

In contrast, individuals with no certificate, diploma, or degree had one of the lowest average employment income levels. Education levels such as college, postsecondary certificates, apprenticeship certificates, and trades certificates showed a similar trend, with average employment income around $40,000 CAD per year.

These results suggest that higher educational attainment is generally associated with higher average employment income in Canada. However, this relationship should not be interpreted as direct causation, since other factors such as occupation, work experience, province, industry, and immigration status may also influence income.

In [ ]:
import os
os.listdir("../images")

In [ ]:
income_by_education_avg[
    [
        "education_level",
        "average_employment_income"
    ]
]

In [ ]:
#create comparative table
income_comparison = df_analysis_clean[
    [
        "education_level",
        "median_employment_income",
        "average_employment_income"
    ]
].copy()

income_comparison["income_difference"] = (
    income_comparison["average_employment_income"] 
    - income_comparison["median_employment_income"]
)

income_comparison = income_comparison.sort_values(
    by="income_difference",
    ascending=False
)

income_comparison

In [ ]:
income_comparison = df_analysis_clean[
    [
        "education_level",
        "median_employment_income",
        "average_employment_income"
    ]
].copy()

income_comparison["income_difference"] = (
    income_comparison["average_employment_income"] 
    - income_comparison["median_employment_income"]
)

income_comparison = income_comparison.sort_values(
    by="income_difference",
    ascending=False
)

income_comparison

The income difference column represents the gap between average employment income and median employment income. A larger difference suggests that the average income may be influenced by individuals with higher earnings within that education group. For example, the degree in medicine, dentistry, veterinary medicine, or optometry category shows the largest difference, with average employment income being $30,400 CAD higher than median employment income.

## Median vs Average Employment Income

This table compares median employment income and average employment income by educational attainment level in Canada in 2020.

The average employment income is generally higher than the median employment income. This suggests that some groups may include individuals with very high incomes, which increases the average. For this reason, the median employment income is useful because it better represents the typical income within each education level.

Overall, comparing both measures provides a more complete understanding of income patterns across educational attainment levels.

In [ ]:
import numpy as np

income_comparison_sorted = income_comparison.sort_values(
    by="median_employment_income",
    ascending=False
)

x = np.arange(len(income_comparison_sorted["education_level"]))
width = 0.35

plt.figure(figsize=(14, 8), facecolor="white")

plt.bar(
    x - width/2,
    income_comparison_sorted["median_employment_income"],
    width,
    label="Median Employment Income"
)

plt.bar(
    x + width/2,
    income_comparison_sorted["average_employment_income"],
    width,
    label="Average Employment Income"
)

plt.xlabel("Educational Attainment", color="black")
plt.ylabel("Employment Income ($)", color="black")
plt.title("Median vs Average Employment Income by Educational Attainment in Canada, 2020", color="black")

plt.xticks(
    x,
    income_comparison_sorted["education_level"],
    rotation=90,
    color="black"
)

plt.yticks(color="black")
plt.legend()

plt.gca().set_facecolor("white")
plt.tight_layout()

plt.savefig(
    "../images/median_vs_average_income_by_education_canada_2020.png",
    bbox_inches="tight",
    facecolor="white"
)

plt.show()

## Interpretation of Median vs Average Employment Income

The chart compares median and average employment income by educational attainment level in Canada in 2020.

In all education groups, the average employment income is higher than the median employment income. This suggests that income distribution may be right-skewed, meaning that some individuals with higher earnings increase the average income.

The largest difference appears in the degree in medicine, dentistry, veterinary medicine, or optometry category, where the average employment income is much higher than the median employment income. This indicates that some individuals in this group may have significantly higher earnings compared with the typical income level.

For this reason, median employment income is useful because it better represents the typical income within each education level, while average employment income helps identify the influence of higher-income earners.

In all education groups, the average employment income is higher than the median employment income. This suggests that income distribution may be right-skewed, meaning that some individuals with higher earnings increase the average income. For this reason, the median employment income is useful because it better represents the typical income within each education level.

In [ ]:
df_analysis_clean[
    [
        "median_employment_income",
        "average_employment_income"
    ]
].describe()

In [ ]:
highest_avg_income = df_analysis_clean.loc[
    df_analysis_clean["average_employment_income"].idxmax(),
    [
        "education_level",
        "average_employment_income"
    ]
]

lowest_avg_income = df_analysis_clean.loc[
    df_analysis_clean["average_employment_income"].idxmin(),
    [
        "education_level",
        "average_employment_income"
    ]
]

print("Highest average income:")
print(highest_avg_income)

print("\nLowest average income:")
print(lowest_avg_income)

In [ ]:
df_analysis_clean.shape

In [ ]:
df_analysis_clean[
    [
        "median_employment_income",
        "average_employment_income"
    ]
].describe()

In [ ]:
highest_avg_income = df_analysis_clean.loc[
    df_analysis_clean["average_employment_income"].idxmax(),
    [
        "education_level",
        "average_employment_income"
    ]
]

lowest_avg_income = df_analysis_clean.loc[
    df_analysis_clean["average_employment_income"].idxmin(),
    [
        "education_level",
        "average_employment_income"
    ]
]

print("Highest average income:")
print(highest_avg_income)

print("\nLowest average income:")
print(lowest_avg_income)

In [ ]:
highest_median_income = df_analysis_clean.loc[
    df_analysis_clean["median_employment_income"].idxmax(),
    [
        "education_level",
        "median_employment_income"
    ]
]

lowest_median_income = df_analysis_clean.loc[
    df_analysis_clean["median_employment_income"].idxmin(),
    [
        "education_level",
        "median_employment_income"
    ]
]

print("Highest median income:")
print(highest_median_income)

print("\nLowest median income:")
print(lowest_median_income)

## Descriptive Statistics

The descriptive statistics summarize the median and average employment income across educational attainment levels in Canada in 2020.

The results show variation in employment income across education levels. The minimum values represent the lowest income levels among the education groups, while the maximum values represent the highest income levels. The standard deviation indicates that income levels are not the same across all education categories.

Overall, these statistics support the idea that educational attainment is associated with differences in employment income.

## Highest and Lowest Employment Income by Education Level

In [ ]:
highest_avg_income = df_analysis_clean.loc[
    df_analysis_clean["average_employment_income"].idxmax(),
    [
        "education_level",
        "average_employment_income"
    ]
]

lowest_avg_income = df_analysis_clean.loc[
    df_analysis_clean["average_employment_income"].idxmin(),
    [
        "education_level",
        "average_employment_income"
    ]
]

print("Highest average income:")
print(highest_avg_income)

print("\nLowest average income:")
print(lowest_avg_income)

In [ ]:
highest_median_income = df_analysis_clean.loc[
    df_analysis_clean["median_employment_income"].idxmax(),
    [
        "education_level",
        "median_employment_income"
    ]
]

lowest_median_income = df_analysis_clean.loc[
    df_analysis_clean["median_employment_income"].idxmin(),
    [
        "education_level",
        "median_employment_income"
    ]
]

print("Highest median income:")
print(highest_median_income)

print("\nLowest median income:")
print(lowest_median_income)

The highest average employment income in Canada in 2020 was observed among individuals with a degree in medicine, dentistry, veterinary medicine, or optometry, with an average employment income of approximately $109,900 CAD per year.

The lowest average employment income was observed among individuals with no certificate, diploma, or degree, with an average employment income of approximately $37,040 CAD per year.

For median employment income, the highest value was observed among individuals with an earned doctorate, with a median employment income of approximately $90,000 CAD per year. The lowest median employment income was observed among individuals with no certificate, diploma, or degree, with a median employment income of approximately $30,000 CAD per year.

These results show a clear difference between the highest and lowest education groups. However, this relationship should not be interpreted as direct causation, since other factors such as occupation, work experience, province, industry, and immigration status may also influence income.

In [10]:
print("Notebook is running correctly")

Notebook is running correctly

In [11]:
import os

print("Current folder:")
print(os.getcwd())

print("\nImages saved:")
print(os.listdir("../images"))

Current folder:
/Users/vanearellano/Documents/GitHub/education-income-canada-analysis/notebooks

Images saved:
['median_vs_average_income_by_education_canada_2020.png', 'median_income_by_education_canada_2020.png', 'average_income_by_education_canada_2020.png']

## Final Conclusion

This project analyzed the association between educational attainment and employment income in Canada in 2020, using Statistics Canada data.

The results show that employment income varies across education levels. Individuals with higher educational attainment, such as earned doctorate, master's degree, bachelor's degree, and professional degrees in medicine, dentistry, veterinary medicine, or optometry, generally show higher median and average employment income.

The analysis also shows that average employment income is higher than median employment income across all education groups. This suggests that income distribution may be right-skewed, meaning that some individuals with higher earnings increase the average income.

Overall, the findings support the idea that educational attainment is associated with employment income in Canada. However, this relationship should not be interpreted as direct causation, since other factors such as occupation, work experience, industry, province, gender, and immigration status may also influence employment income.

As a future extension, this project could analyze how immigrant status is associated with employment income while also considering educational attainment.